### ISSUE TITLE
Unknown_root.pluginlist not found

### ISSUE THREAD

**Issue by duckly** [liyi-david/ePMC#1]
Hi all, 
I tried to run the JUnit tests in epmc-tests and got message 
   "Plugin list file "Unknown_root.pluginlist" not found."
Is it missing in the project?

**Comment by andreat** [comment]
Actually, the file is not really missing, since it is of the form "hostname[.domain]"_"username".pluginlist and everyone running the JUnit tests should create a custom one, by taking inspiration from the ones already present in tests/src/test/resources/

**Comment by duckly** [comment]
Thanks, but some times it reported that prism examples are missing as follows:

java.lang.RuntimeException: java.io.FileNotFoundException: MY_HOME/prism-examples/cluster/cluster.sm (No such file or directory)
do you put prism-examples folder somewhere?

**Comment by andreat** [comment]
I have updated the tests/README.md file to cover also this aspect
