### ISSUE TITLE
Java 9

### ISSUE THREAD

**Issue by cdehnert** [liyi-david/ePMC#2]
Dear ePMC-Team,

I'm having trouble to build ePMC using Java 9. For Java 8 it works fine, but ePMC's dependency proguard does not seem to be compatible with Java 9 at the moment.

Would it be possible to optionally disable proguard (using a command-line flag or similar) so that ePMC builds also under Java 9?

Thanks and best wishes,
Chris

**Comment by andreat** [comment]
Hi Chris,

I am not sure whether proguard can be disabled, since it is used to manage the packaging of the plugins. 
@ernstmoritzhahn should know better about this, but he is probably busy these days.

Regards,
Andrea

**Comment by ernstmoritzhahn** [comment]
Hi,

sorry for the late reply. I'll take a look.

Best regards,
Moritz

**Comment by andreat** [comment]
After the latest changes, proguard is no more used and ePMC compiles and works with JAVA 10.
